### ISSUE TITLE
Alternative netbox.netbox.nb_inventory_inventory

### ISSUE THREAD

**Issue by ypid** [Sidarion/netbox-joined-inventory#5]
It looks to me that this script got deprecated by https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/inventory/nb_inventory/netbox.netbox.nb_inventory_inventory.html. The reason I looked into netbox-joined-inventory was that it provides a nice way to generate inventory files that one can review. I have now tested a way to get a similar behavior with `netbox.netbox.nb_inventory`:

`ansible/inventory/netbox.yml`:
```yaml
---
# vim: foldmarker=[[[,]]]:foldmethod=marker

plugin: netbox.netbox.nb_inventory
token: invalid
## More netbox.netbox.nb_inventory settings.

## 60 * 60 * 24 * 360 * 1000
cache_timeout: 31104000000
```

`ansible/refresh-netbox.yml`:
```yaml
---
# vim: foldmarker=[[[,]]]:foldmethod=marker

plugin: netbox.netbox.nb_inventory
## More netbox.netbox.nb_inventory settings.

cache_timeout: 10
```

`ansible.cfg`:
```ini
[inventory]
cache = True
cache_plugin = jsonfile
cache_connection = ~/.ansible/inventory_cache
```

`Makefile`:
```Makefile
.PHONY: refresh-netbox
refresh-netbox: ansible/inventory/netbox.yml
	@echo "## This file is managed by a Makefile, all changes will be lost.\n" > ansible/refresh-netbox.yml
	sed 's/^cache_timeout:.*/cache_timeout: 10/;/^token: invalid$$/d;s/^# real token:/token:/;' "$<" >> ansible/refresh-netbox.yml
	ansible-inventory -v --list -i ansible/refresh-netbox.yml | less
	git -C ~/.ansible/inventory_cache diff
	git -C ~/.ansible/inventory_cache add .
	git -C ~/.ansible/inventory_cache commit -m "Auto commit after review"
```

To refresh the cache, run `ansible-inventory -v --list -i ansible/refresh-netbox.yml` and then review the changes in `~/.ansible/inventory_cache` or `make refresh-netbox`.

You could also use `ansible-playbook --diff --check` in combination with manual cache refresh.

What do you think?
